# Generated by Django 3.2.9 on 2021-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_items_options'),
        ('buyers', '0002_alter_buyers_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyers',
            options={'verbose_name_plural': 'Buyers'},
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='item',
        ),
        migrations.AddField(
            model_name='buyers',
            name='item',
            field=models.ManyToManyField(related_name='items', to='items.Items'),
        ),
    ]
