# Generated by Django 3.2.9 on 2021-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_items_options'),
        ('buyers', '0003_auto_20211114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='item',
            field=models.ManyToManyField(related_name='buyers', to='items.Items'),
        ),
    ]
