# Generated by Django 3.2.9 on 2021-11-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_auto_20211114_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
