# Generated by Django 3.2.9 on 2021-11-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyers_item'),
        ('items', '0002_items_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyers.buyers'),
        ),
    ]
