# Generated by Django 3.2.9 on 2021-11-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_sold_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
    ]
